config/routes.rb
Decoshows::Application.routes.draw do
  devise_for :users, :path => "cms", :path_names => { :sign_in => 'login', :sign_out => 'logout', :password => 'secret', :confirmation => 'verification', :unlock => 'unblock', :registration => 'register', :sign_up => 'cmon_let_me_in' }

  resources :albumes do
    resources :fotos
  end

  resources :metas

  root :to => "albumes#index"
end

app/models/album.rb
class Album < ActiveRecord::Base
  has_many :fotos, :dependent => :destroy
  validates :nombre, :presence => true, :length => { :maximum => 244 } 
end

app/models/foto.rb
class Foto < ActiveRecord::Base
  belongs_to :album
  
  validates_attachment_content_type :foto, :content_type =>  ['image/png', 'image/jpg', 'image/jpeg']
  validates_attachment_size :foto, :less_than => 4.megabytes
  validates_attachment_presence :foto
  has_attached_file :foto, :styles => { :thumb => ["211x138#", :jpg], :regular => ["900x598>", :jpg] },
                            :url  => "/system/assets/fotos/:id/:style/:basename.:extension",
                            :path => ":rails_root/public/system/assets/fotos/:id/:style/:basename.:extension"
end

app/models/meta.rb
class Meta < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :registerable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/albumes_controller.rb
class AlbumesController < InheritedResources::Base
  
  def index
    @album = Album.new
    @albumes = Album.all
  end
  
  def create
    create!(:notice => "Su álbum fue creado con éxito.") { @album }
  end
  
  def update
    update!(:notice => "Álbum actualizado con éxito.") { root_url }
  end
  
  def destroy
    destroy!(:notice => "Álbum eliminado con éxito.") { root_url }
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/fotos_controller.rb
class FotosController < InheritedResources::Base
  def create
    @album = Album.find(params[:album_id])
    @foto = Foto.new(params[:foto])
    
    if @foto.save
      @album.fotos << @foto
      flash[:notice] = "Foto agregada correctamente."
      redirect_to album_url(@album)
    else
      flash[:notice] = "Hubo un error, inténtalo de nuevo"
      redirect_to album_url(@album)
    end
   
  end
  
  def destroy
    _find_album
    @foto = @album.fotos.find(params[:id])
    @foto.destroy
    flash[:notice] = "Foto eliminada."
    redirect_to albums_url
  end
  
  def _find_album
    @album = Album.find(params[:album_id])
  end
  
  protected
  
  def collection
    @fotos ||= end_of_association_chain.paginate(:page => params[:page], :per_page => 12)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/metas_controller.rb
class MetasController < InheritedResources::Base
end

app/helpers/albumes_helper.rb
module AlbumesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fotos_helper.rb
module FotosHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/metas_helper.rb
module MetasHelper
end

app/views/albumes/_form.html.erb
<%= form_for(@album) do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="actions">
    <%= f.submit "Actualizar Álbum" %>
  </div>
<% end %>

app/views/albumes/edit.html.erb
<h1>Editing album</h1>

<%= render 'form' %>

<%= link_to 'Show', @album %> |
<%= link_to 'Back', albumes_path %>

app/views/albumes/index.html.erb
<% if current_user %>
<h2>Crear un nuevo álbum</h2>
<h5><%= link_to "Cerrar sesión", destroy_user_session_path, :method => :delete %></h5>

<p id="notice"><%= notice %></p>

<%= form_for @album, :url => {:action => 'create'}  do |f| %>
  <% if @album.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@album.errors.count, "error") %> prohibited this album from being saved:</h2>

      <ul>
      <% @album.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre, "Nombre" %><br />
    <%= f.text_field :nombre %>
  </div>
  <div class="actions">
    <%= f.submit "Crear Álbum" %>
  </div>
<% end %>
<% end %>

<ul>
<% if @albumes.any? %>	
<% @albumes.each do |album| %>
  <li class="<%= cycle('break', '', '', 'last') %>">
	<% if album.fotos.any? %>
	<%= link_to truncate(album.nombre, :length => 32), album %>
	<br />
	<%= link_to image_tag(album.fotos.first.foto(:thumb)), album %>
	<% else %>
    <%= link_to truncate(album.nombre, :length => 32), album %>
    <% end %>
  <% if current_user %>
  <br />
    <%= link_to 'Cambiar nombre', edit_album_path(album) %>
    <%= link_to 'Eliminar álbum', album, :confirm => '¿Estás seguro? Se borraran todas las fotos que están en álbum', :method => :delete %>
  <% end %>
  </li>
<% end %>
<% else %>
No hay ningún álbum creado.
<% end %>
</ul>

app/views/albumes/new.html.erb
<h1>New album</h1>

<%= render 'form' %>

<%= link_to 'Back', albumes_path %>

app/views/albumes/show.html.erb
<% content_for :javascript do %>
  <%= stylesheet_link_tag '/javascripts/libs/lightbox/themes/white-green/jquery.lightbox.css' %>
  <%= javascript_include_tag '/javascripts/libs/lightbox/jquery.lightbox.min.js' %>
  <script type="text/javascript">
    $(document).ready(function() {
      jQuery('.lightbox').lightbox();
    })
  </script>
<% end %>

<% if current_user %>
<p id="notice"><%= notice %></p>
<h2>Agregar una nueva foto</h2>
<h5><%= link_to "Cerrar sesión", destroy_user_session_path, :method => :delete %></h5>
  <%= form_for(:foto, :url => album_fotos_url(@album), :html => { :multipart => true }) do |f| %>
    <div class="field">
      <%= f.label :foto, "Foto" %><br />
      <%= f.file_field :foto %>
    </div>
    <div class="actions">
      <%= f.submit "Guardar" %>
    </div>
  <% end %>
<% end %>
<p>
  <h1><%= @album.nombre %></h1>
</p>

<ul>
<% if @album.fotos %>
  <% @album.fotos.each do |foto| %>
    <li class="<%= cycle('break', '', '', 'last') %>">
      <%= link_to image_tag(foto.foto(:thumb)), foto.foto(:regular), :class => 'lightbox', :rel => 'gallery' %>
      <% if current_user %>
      <br />
      <%= link_to 'Eliminar', album_foto_url(@album, foto), :confirm => '¿Estás seguro?', :method => :delete %>
      <% end %>
  </li>
  <% end %>
<% end %>
</ul>
<div class="controles">
<% if current_user %>
<%= link_to 'Cambiar nombre al álbum', edit_album_path(@album), :class => 'btn rename' %> |
<% end %>
<%= link_to 'Volver', albumes_path, :class => 'btn back' %>
</div>

app/views/fotos/_form.html.erb
<%= form_for(@foto) do |f| %>
  <% if @foto.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@foto.errors.count, "error") %> prohibited this foto from being saved:</h2>

      <ul>
      <% @foto.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fotos/edit.html.erb
<h1>Editing foto</h1>

<%= render 'form' %>

<%= link_to 'Show', @foto %> |
<%= link_to 'Back', fotos_path %>

app/views/fotos/index.html.erb
<h1>Listing fotos</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @fotos.each do |foto| %>
  <tr>
    <td><%= link_to 'Show', foto %></td>
    <td><%= link_to 'Edit', edit_foto_path(foto) %></td>
    <td><%= link_to 'Destroy', foto, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Foto', new_foto_path %>

app/views/fotos/new.html.erb
<h1>New foto</h1>

<%= render 'form' %>

<%= link_to 'Back', fotos_path %>

app/views/fotos/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_foto_path(@foto) %> |
<%= link_to 'Back', fotos_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Decoshows</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= yield :javascript %>

  <%= csrf_meta_tag %>

</head>
<body>

<div id="decoshow-iframe">
<%= yield %>
</div>
</body>
</html>
<%#= render :partial => 'shared/google_analytics' %>

app/views/metas/_form.html.erb
<%= form_for(@meta) do |f| %>
  <% if @meta.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meta.errors.count, "error") %> prohibited this meta from being saved:</h2>

      <ul>
      <% @meta.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :keywords %><br />
    <%= f.text_field :keywords %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/metas/edit.html.erb
<h1>Editing meta</h1>

<%= render 'form' %>

<%= link_to 'Show', @meta %> |
<%= link_to 'Back', metas_path %>

app/views/metas/index.html.erb
<h1>Listing metas</h1>

<table>
  <tr>
    <th>Keywords</th>
    <th>Description</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @metas.each do |meta| %>
  <tr>
    <td><%= meta.keywords %></td>
    <td><%= meta.description %></td>
    <td><%= link_to 'Show', meta %></td>
    <td><%= link_to 'Edit', edit_meta_path(meta) %></td>
    <td><%= link_to 'Destroy', meta, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Meta', new_meta_path %>

app/views/metas/new.html.erb
<h1>New meta</h1>

<%= render 'form' %>

<%= link_to 'Back', metas_path %>

app/views/metas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Keywords:</b>
  <%= @meta.keywords %>
</p>

<p>
  <b>Description:</b>
  <%= @meta.description %>
</p>


<%= link_to 'Edit', edit_meta_path(@meta) %> |
<%= link_to 'Back', metas_path %>

app/views/shared/_google_analytics.html.erb
<script type="text/javascript" charset="utf-8">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'INSERT-URCHIN-CODE']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>